integrations:
- integration_type: git_repo
  git_repo: mosaicml/llm-foundry
  git_branch: main
  pip_install: -e .[gpu]

command: |
  cd llm-foundry/scripts
  python data_prep/convert_dataset_hf.py \
    --dataset c4 --data_subset en \
    --out_root ./my-copy-c4 --splits train_small val_small \
    --concat_tokens 2048 --tokenizer EleutherAI/gpt-neox-20b --eos_text '<|endoftext|>'
  composer train/train.py /mnt/config/parameters.yaml \
    max_duration=10ba \
    train_loader.dataset.split=train_small \
    eval_loader.dataset.split=val_small
  composer train/train.py /mnt/config/parameters.yaml \
    max_duration=20ba \
    autoresume=true \
    train_loader.dataset.split=train_small \
    eval_loader.dataset.split=val_small

image: mosaicml/pytorch:2.0.1_cu118-python3.10-ubuntu20.04
name: mpt-125m-sharded-regression

compute:
  gpus: 8

parameters:
  run_name: mpt-125m-sharded-regression
  data_local: ./my-copy-c4
  data_remote:
  max_seq_len: 2048
  global_seed: 17

  model:
    name: mpt_causal_lm
    init_device: meta
    d_model: 768
    n_heads: 12
    n_layers: 12
    expansion_ratio: 4
    max_seq_len: ${max_seq_len}
    vocab_size: 50368
    attn_config:
      attn_impl: triton

  tokenizer:
    name: EleutherAI/gpt-neox-20b
    kwargs:
      model_max_length: ${max_seq_len}

  train_loader:
    name: text
    dataset:
      local: ${data_local}
      remote: ${data_remote}
      split: train
      shuffle: true
      max_seq_len: ${max_seq_len}
      shuffle_seed: ${global_seed}
    drop_last: true
    num_workers: 8

  eval_loader:
    name: text
    dataset:
      local: ${data_local}
      remote: ${data_remote}
      split: val
      shuffle: false
      max_seq_len: ${max_seq_len}
      shuffle_seed: ${global_seed}
    drop_last: false
    num_workers: 8

  scheduler:
    name: cosine_with_warmup
    t_warmup: 100ba
    alpha_f: 0.1

  optimizer:
    name: decoupled_adamw
    lr: 6.0e-4
    betas:
    - 0.9
    - 0.95
    eps: 1.0e-08
    weight_decay: 0.0

  algorithms:
    gradient_clipping:
      clipping_type: norm
      clipping_threshold: 1.0

  max_duration: 4800ba
  eval_interval: 500ba
  eval_first: false
  eval_subset_num_batches: -1
  global_train_batch_size: 256

  seed: ${global_seed}
  device_eval_batch_size: 16
  device_train_microbatch_size: auto
  precision: amp_bf16

  fsdp_config:
    sharding_strategy: FULL_SHARD
    mixed_precision: PURE
    activation_checkpointing: false
    activation_checkpointing_reentrant: false
    activation_cpu_offload: false
    limit_all_gathers: true
    verbose: false
    state_dict_type: sharded

  progress_bar: false
  log_to_console: true
  console_log_interval: 1ba

  callbacks:
    speed_monitor:
      window_size: 10
    lr_monitor: {}
    memory_monitor: {}
    runtime_estimator: {}

  save_interval: 500ba
  save_folder: ./{run_name}/checkpoints
