integrations:
- integration_type: git_repo
  git_repo: mosaicml/llm-foundry
  git_branch: v0.5.0
  # git_commit:  # OR use your commit hash
  pip_install: -e .
  ssh_clone: false  # Should be true if using a private repo

command: |
  cd llm-foundry/scripts/inference
  python convert_composer_to_hf.py \
    --composer_path s3://bucket/folder/checkpoint-path.pt \
    --hf_output_path s3://bucket/folder/hf/ \
    --output_precision bf16 \

image: mosaicml/llm-foundry:2.2.0_cu121_flash2-latest
name: convert-composer-hf

compute:
  gpus: 8  # Number of GPUs to use

  ## These configurations are optional
  # cluster: TODO # Name of the cluster to use for this run
  # gpu_type: a100_80gb # Type of GPU to use. We use a100_80gb in our experiments
