seed: 17
model:
  name: hf_causal_lm
  pretrained: false
  init_device: meta
  peft_config:
    r: 64
    peft_type: LORA
    task_type: CAUSAL_LM
    lora_alpha: 32
    lora_dropout: 0.05
    target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
  use_auth_token: true
  config_overrides: {}
  trust_remote_code: true
  use_train_metrics: true
  should_save_peft_only: false
  use_flash_attention_2: true
  pretrained_model_name_or_path: meta-llama/Meta-Llama-3.1-405B-Instruct
loggers: {}
metadata:
  run_group: b200-benchmark-prep
run_name: llama405b-8192-meta-4
callbacks:
  lr_monitor: {}
  scheduled_gc:
    batch_interval: 1000
  speed_monitor:
    window_size: 1
  memory_monitor: {}
  runtime_estimator: {}
icl_tasks: []
load_path: null
optimizer:
  lr: 1.0e-06
  name: decoupled_lionw
  betas:
  - 0.9
  - 0.95
  weight_decay: 1.0e-06
precision: amp_bf16
scheduler:
  name: cosine_with_warmup
  alpha_f: 0
  t_warmup: 0.02dur
tokenizer:
  name: meta-llama/Meta-Llama-3.1-405B-Instruct
  kwargs:
    revision: main
    model_max_length: 8192
    model_input_names:
    - input_ids
    - attention_mask
    trust_remote_code: true
algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1
autoresume: true
code_paths: []
eval_first: false
log_config: true
fsdp_config:
  verbose: true
  mixed_precision: PURE
  state_dict_type: sharded
  use_orig_params: true
  forward_prefetch: false
  backward_prefetch: BACKWARD_POST
  limit_all_gathers: true
  sharding_strategy: FULL_SHARD
  sync_module_states: false
  activation_cpu_offload: true
  activation_checkpointing: true
  load_monolith_rank0_only: true
  activation_checkpointing_reentrant: false
icl_seq_len: 1024
max_seq_len: 8192
save_folder: ./local-ckpts
dist_timeout: 600
max_duration: 50ba
progress_bar: false
train_loader:
  name: text
  dataset:
    shuffle: true
    streams:
      local:
        local: /data/my-copy
        split: train_small
        remote: ''
    max_seq_len: 8192
    predownload: null
    eos_token_id: 128009
    shuffle_seed: 17
    shuffle_block_size: null
    num_canonical_nodes: null
  drop_last: true
  pin_memory: true
  num_workers: 8
  prefetch_factor: 2
  persistent_workers: true
eval_interval: 1ep
save_interval: 1ep
log_to_console: true
save_overwrite: false
load_ignore_keys: null
python_log_level: debug
save_ignore_keys: null
load_weights_only: false
save_weights_only: false
only_hf_checkpoint: false
console_log_interval: 1ba
device_eval_batch_size: 1
eval_subset_num_batches: 20
global_train_batch_size: 64
only_composer_checkpoint: false
device_train_microbatch_size: 1
save_num_checkpoints_to_keep: 1
accumulate_train_batch_on_tokens: true

# python /llm-foundry/scripts/data_prep/convert_dataset_hf.py --dataset allenai/c4 --data_subset en --out_root /data/my-copy --splits train_small val_small --concat_tokens 8192 --tokenizer meta-llama/Meta-Llama-3.1-405B-Instruct --eos_text '<|eot_id|>'
# cd /llm-foundry && composer -n 8 scripts/train/train.py /mnt/config/parameters.yaml || (echo "Command failed - killing python" && pkill -f python && exit 1)
# echo exit code is $?
