# Modified t5-small_dolly_sft.yaml file to get it running using ComposerHFT5 wrapper class

variables:
  global_seed: 17
  model_name: google-t5/t5-small
  save_folder: /mnt/workdisk/kushal/llm-foundry-fork/tmp/output/t5-small-1

  max_seq_len: 1024

  # Run Name
  run_name:  # If left blank, will be read from env var $RUN_NAME

max_seq_len: ${variables.max_seq_len}
run_name: ${variables.run_name}

# Model
model:
  name: hf_t5
  pretrained_model_name_or_path: ${variables.model_name}
  pretrained: true

# Tokenizer
tokenizer:
  name: ${variables.model_name}

# Dataloaders
train_loader:
  name: finetuning
  dataset:
    hf_name: HuggingFaceH4/databricks_dolly_15k
    split: train
    max_seq_len: ${variables.max_seq_len}
    allow_pad_trimming: false
    decoder_only_format: false
    shuffle: true
  drop_last: true
  num_workers: 8
  pin_memory: false
  prefetch_factor: 2
  persistent_workers: true
  timeout: 0

# There is no validation split so we skip eval_loader

# Optimization
scheduler:
  name: linear_decay_with_warmup  # linear no warmup is HF default which dolly used
  t_warmup: 0ba
  alpha_f: 0

optimizer:
  # mimic HF defaults to replicate dolly
  name: decoupled_adamw
  lr: 1.0e-5
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-8
  weight_decay: 0

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0

max_duration: 2ba #1ep
eval_interval: 1  # this is the only allowed value for no eval
# eval_first: false
# eval_subset_num_batches: -1
global_train_batch_size: 64  # assuming 8 gpus

# System
seed: ${variables.global_seed}
device_eval_batch_size: 8
device_train_microbatch_size: 8
# device_train_microbatch_size: auto
precision: amp_bf16

# FSDP
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: PURE
  activation_checkpointing: true
  activation_checkpointing_reentrant: false
  activation_cpu_offload: false
  limit_all_gathers: true

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 1ba

callbacks:
  speed_monitor:
    window_size: 10
  lr_monitor: {}
  memory_monitor: {}
  runtime_estimator: {}

loggers:
  mlflow:
    tags:
      group: 
    tracking_uri: databricks
    experiment_name: /Users/kushal.kodnad+intern@databricks.com/t5-small-experiment

# Checkpoint to local filesystem or remote object store
save_interval: 1ba
# save_num_checkpoints_to_keep: 1  # Important, this cleans up checkpoints saved to DISK
# save_folder: ./{run_name}/checkpoints
# save_folder: s3://my-bucket/my-folder/{run_name}/checkpoints
save_folder: ${variables.save_folder}

# Load from remote object store
# REPLACE THE BELOW with you own checkpoint!
# load_path: oci://my-bucket/my-folder/checkpoints/some_checkpoint.pt
# load_weights_only: true  # Only load the weights, not the optimizer state, LR schedule, etc
load_weights_only: false  # Only load the weights, not the optimizer state, LR schedule, etc

save_overwrite: true # overwrite any checkpoints in the current folder; cannot be true when `autoresume: true`
# autoresume: true # set to true if we want to autoresume from the load_path or latest checkpoint
