integrations:
  - integration_type: git_repo
    git_repo: mosaicml/examples
    git_branch: v0.0.2
    pip_install: -r llm/requirements.txt

# We are fetching, converting, and training on the 'val' split
# as it is small and quick to get going for this demo.
# For real training runs, follow the instructions in `examples/llm/README.md`
# to convert and host the full 'train' dataset.
command: |
  cd examples/llm
  python convert_c4.py --out_root ./my-copy-c4 --splits val
  composer main.py /mnt/config/parameters.yaml

image: mosaicml/pytorch:1.12.1_cu116-python3.9-ubuntu20.04
optimization_level: 0

run_name: mosaic-gpt-1b-ctx-8k-gpus-8

gpu_num: 8
gpu_type: a100_40gb
cluster: r0z0 # replace with your cluster here!

# The below is injected as a YAML file: /mnt/config/parameters.yaml
# and referenced in our `command` above
# We use this to customize hparams like `max_seq_len=8192` at runtime
parameters:
  data_remote: &data_remote ./my-copy-c4
  data_local: &data_local ./my-copy-c4
  max_seq_len: &max_seq_len 8192
  tokenizer_name: &tokenizer_name gpt2

  # Model
  model:
    name: mosaic_gpt
    device: meta
    tokenizer_name: *tokenizer_name
    d_model: 2048
    n_heads: 16 # Modified 24->16 so that d_head == 128 to statisfy FlashAttention
    n_layers: 24
    mlp_ratio: 4
    max_seq_len: *max_seq_len
    vocab_size: 50257
    init_std: 0.02
    attn_pdrop: 0.0
    resid_pdrop: 0.0
    emb_pdrop: 0.0
    attn_impl: flash

  # Tokenizer
  tokenizer:
    type: hftokenizer
    args:
      tokenizer_name: *tokenizer_name
      max_seq_len: *max_seq_len

  # Dataloaders
  train_loader:
    dataset:
      remote: *data_remote
      local: *data_local
      split: val # Using the 'val' split for this demo
      shuffle: true
      prefetch: 1_000_000
      tokenizer_name: *tokenizer_name
      max_seq_len: *max_seq_len
      group_method: concat
    drop_last: true
    num_workers: 8
    pin_memory: true
    prefetch_factor: 2
    persistent_workers: true
    timeout: 0

  eval_loader:
    dataset:
      remote: *data_remote
      local: *data_local
      split: val
      shuffle: false
      prefetch: 1000
      tokenizer_name: *tokenizer_name
      max_seq_len: *max_seq_len
      group_method: truncate
    drop_last: false
    num_workers: 8
    pin_memory: true
    prefetch_factor: 2
    persistent_workers: true
    timeout: 0

  # Optimization
  scheduler:
    name: cosine_with_warmup
    t_warmup: 100ba
    alpha_f: 0.1

  optimizer:
    name: decoupled_adamw
    lr: 2.0e-4
    betas:
    - 0.9
    - 0.95
    eps: 1.0e-08
    weight_decay: 0.0

  max_duration: 24800ba # ~ 26B tokens
  eval_interval: 2000ba
  global_train_batch_size: 128 # ~1M tokens
  grad_clip_norm: 1.0

  # System
  seed: 17
  device_eval_batch_size: 2
  device_train_microbatch_size: auto
  precision: bf16

  # FSDP
  fsdp_config:
    sharding_strategy: FULL_SHARD
    min_params: 2e8
    mixed_precision: DEFAULT
    activation_checkpointing: true
    activation_cpu_offload: false
    verbose: true

  # Logging
  progress_bar: false
  log_to_console: true

  callbacks:
    speed_monitor:
      window_size: 10
    lr_monitor: {}
    memory_monitor: {}

  # loggers:
  #   wandb: {}

  # Checkpoint to local filesystem or remote object store
  # save_interval: 2000ba
  # save_num_checkpoints_to_keep: 1  # Important, this cleans up checkpoints saved to DISK
  # save_folder: ./{run_name}/checkpoints
  # save_folder: s3://my-bucket/my-folder/{run_name}/checkpoints

  # Load from local filesystem or remote object store
  # load_path: ./gpt-1b/checkpoints/latest-rank{rank}.pt
  # load_path: s3://my-bucket/my-folder/gpt-1b/checkpoints/latest-rank{rank}.pt
