icl_tasks:
-
  label: human_eval
  dataset_uri: eval/local_data/programming/human_eval.jsonl # ADD YOUR OWN DATASET URI
  num_fewshot: [0]
  pass_at_k: 1
  num_beams: 20
  icl_task_type: code_evaluation
  batch_size: 1

-
  label: human_eval_cpp
  dataset_uri: eval/local_data/programming/processed_human_eval_cpp.jsonl # ADD YOUR OWN DATASET URI
  num_fewshot: [0]
  pass_at_k: 1
  num_beams: 20
  icl_task_type: code_evaluation
  batch_size: 1
-
  label: human_eval_js
  dataset_uri: eval/local_data/programming/processed_human_eval_js.jsonl # ADD YOUR OWN DATASET URI
  num_fewshot: [0]
  pass_at_k: 1
  num_beams: 20
  icl_task_type: code_evaluation
  batch_size: 1
