icl_tasks:
  -
    label: jeopardy
    dataset_uri: eval/local_data/jeopardy_all.jsonl # ADD YOUR OWN DATASET URI
    num_fewshot:
    - 0
    - 1
    - 5
    - 10
    batch_size: 8
    icl_task_type: language_modeling
    metric_names:
    - InContextLearningLMAccuracy
    prompt_string: "" # this goes at the beginning of each input
    example_delimiter: "\n" # this goes between fewshot examples
    continuation_delimiter: "\nAnswer: " # this separates questions from answers
    has_categories: true
  -
    label: lambada_openai
    dataset_uri: eval/local_data/lambada_openai.jsonl
    num_fewshot:
    - 0
    batch_size: 8
    icl_task_type: language_modeling
    metric_names:
    - InContextLearningLMAccuracy
    prompt_string: "" # this goes at the beginning of each input
    example_delimiter: "\n" # this goes between fewshot examples
    continuation_delimiter: " " # this separates contexts from continuations
  -
    label: piqa
    dataset_uri:  eval/local_data/piqa.jsonl  # ADD YOUR OWN DATASET URI
    num_fewshot:
    - 0
    - 1
    - 5
    - 10
    batch_size: 8
    icl_task_type: multiple_choice
    metric_names:
    - InContextLearningMultipleChoiceAccuracy
    prompt_string: "" # this goes at the beginning of each input
    example_delimiter: "\n" # this goes between fewshot examples
    continuation_delimiter: "Answer: " # this separates questions from answers
  -
    label: hellaswag
    dataset_uri: eval/local_data/hellaswag.jsonl # ADD YOUR OWN DATASET URI
    num_fewshot:
    - 0
    - 1
    - 5
    - 10
    batch_size: 8
    icl_task_type: multiple_choice
    metric_names:
    - InContextLearningMultipleChoiceAccuracy
    prompt_string: "" # this goes at the beginning of each input
    example_delimiter: "\n" # this goes between fewshot examples
    continuation_delimiter: " " # this separates questions from answers
  -
    label: arc_easy
    dataset_uri: eval/local_data/arc_easy.jsonl # ADD YOUR OWN DATASET URI
    num_fewshot:
    - 0
    - 1
    - 5
    - 10
    batch_size: 8
    icl_task_type: multiple_choice
    metric_names:
    - InContextLearningMultipleChoiceAccuracy
    prompt_string: "" # this goes at the beginning of each input
    example_delimiter: "\n" # this goes between fewshot examples
    continuation_delimiter: "Answer: " # this separates questions from answers
  -
    label: arc_challenge
    dataset_uri: eval/local_data/arc_challenge.jsonl # ADD YOUR OWN DATASET URI
    num_fewshot:
    - 0
    - 1
    - 5
    - 10
    batch_size: 8
    icl_task_type: multiple_choice
    metric_names:
    - InContextLearningMultipleChoiceAccuracy
    prompt_string: "" # this goes at the beginning of each input
    example_delimiter: "\n" # this goes between fewshot examples
    continuation_delimiter: "Answer: " # this separates questions from answers
  -
    label: copa
    dataset_uri: eval/local_data/copa.jsonl # ADD YOUR OWN DATASET URI
    num_fewshot:
    - 0
    - 1
    - 5
    - 10
    batch_size: 8
    icl_task_type: multiple_choice
    metric_names:
    - InContextLearningMultipleChoiceAccuracy
    prompt_string: "" # this goes at the beginning of each input
    example_delimiter: "\n" # this goes between fewshot examples
    continuation_delimiter: " " # this separates questions from answers
  -
    label: boolq
    dataset_uri: eval/local_data/boolq.jsonl # ADD YOUR OWN DATASET URI
    num_fewshot:
    - 0
    - 1
    - 5
    - 10
    batch_size: 8
    icl_task_type: multiple_choice
    metric_names:
    - InContextLearningMultipleChoiceAccuracy
    prompt_string: "" # this goes at the beginning of each input
    example_delimiter: "\n" # this goes between fewshot examples
    continuation_delimiter: "Answer: " # this separates questions from answers
  -
    label: mmlu
    dataset_uri: eval/local_data/mmlu.jsonl # ADD YOUR OWN DATASET URI
    num_fewshot:
    - 0
    - 1
    - 5
    - 10
    batch_size: 8
    icl_task_type: multiple_choice
    metric_names:
    - InContextLearningMultipleChoiceAccuracy
    prompt_string: "" # this goes at the beginning of each input
    example_delimiter: "\n" # this goes between fewshot examples
    continuation_delimiter: "Answer: " # this separates questions from answers
    has_categories: true
  -
    label: winograd
    dataset_uri: eval/local_data/winograd_wsc.jsonl # ADD YOUR OWN DATASET URI
    num_fewshot:
    - 0
    - 1
    - 5
    - 10
    batch_size: 8
    icl_task_type: schema
    metric_names:
    - InContextLearningMultipleChoiceAccuracy
    prompt_string: "" # this goes at the beginning of each input
    example_delimiter: "\n" # this goes between fewshot examples
    continuation_delimiter: " " # this separates questions from answers
  -
    label: winogrande
    dataset_uri: eval/local_data/winogrande.jsonl # ADD YOUR OWN DATASET URI
    num_fewshot:
    - 0
    - 1
    - 5
    - 10
    batch_size: 8
    icl_task_type: schema
    metric_names:
    - InContextLearningMultipleChoiceAccuracy
    prompt_string: "" # this goes at the beginning of each input
    example_delimiter: "\n" # this goes between fewshot examples
    continuation_delimiter: " " # this separates questions from answers
  -
    label: triviaqa
    dataset_uri: eval/local_data/triviaqa.jsonl # ADD YOUR OWN DATASET URI
    num_fewshot:
    - 0
    - 1
    - 5
    - 10
    batch_size: 8
    icl_task_type: question_answering
    metric_names:
    - InContextLearningQAAccuracy
    prompt_string: "" # this goes at the beginning of each input
    example_delimiter: "\n" # this goes between fewshot examples
    continuation_delimiter: " " # this separates questions from answers
