tokenizer:
  type: hftokenizer
  args:
    tokenizer_name: gpt2
    max_seq_len: 2048

model:
  name: mosaic_gpt
  init_device: meta
  tokenizer_name: gpt2
  d_model: 768
  n_heads: 12
  n_layers: 12
  mlp_ratio: 4
  max_seq_len: 2048
  vocab_size: 50257
  init_std: 0.02
  attn_pdrop: 0.0
  resid_pdrop: 0.0
  emb_pdrop: 0.0
  attn_impl: flash

load_path: # Add your (optional) Composer checkpoint path here!

# FSDP config for model sharding
# fsdp_config:
#   sharding_strategy: FULL_SHARD

icl_tasks:
-
  label: piqa
  dataset_uri: # ADD YOUR OWN DATASET URI
  num_fewshot:
  - 5
  batch_size: 16
  icl_task_type: multiple_choice
  metric_names:
  - InContextLearningMultipleChoiceAccuracy
  prompt_string: '' # this goes at the beginning of each input
  example_delimiter: '\n' # this goes between fewshot examples
  continuation_delimiter: ' ' # this separates questions from answers
-
  label: lambada
  dataset_uri: # ADD YOUR OWN DATASET URI
  num_fewshot:
  - 0
  batch_size: 16
  icl_task_type: language_modeling
  metric_names:
  - InContextLearningLMAccuracy
  prompt_string: '' # this goes at the beginning of each input
  example_delimiter: '\n' # this goes between fewshot examples
  continuation_delimiter: '' # this separates contexts from continuations
