max_seq_len: 2048
tokenizer_name: gpt2

# Tokenizer
tokenizer:
  name: ${tokenizer_name}
  kwargs:
    model_max_length: 2048

model:
  name: mosaic_gpt
  init_device: meta
  tokenizer_name: ${tokenizer_name}
  d_model: 768
  n_heads: 12
  n_layers: 12
  mlp_ratio: 4
  max_seq_len: ${max_seq_len}
  vocab_size: 50368
  attn_impl: triton

load_path: # Add your (optional) Composer checkpoint path here!

# FSDP config for model sharding
# fsdp_config:
#   sharding_strategy: FULL_SHARD
#   mixed_precision: PURE

icl_tasks:
-
  label: piqa
  dataset_uri: # ADD YOUR OWN DATASET URI
  num_fewshot:
  - 5
  batch_size: 16
  icl_task_type: multiple_choice
  metric_names:
  - InContextLearningMultipleChoiceAccuracy
  prompt_string: '' # this goes at the beginning of each input
  example_delimiter: '\n' # this goes between fewshot examples
  continuation_delimiter: ' ' # this separates questions from answers
-
  label: lambada
  dataset_uri: # ADD YOUR OWN DATASET URI
  num_fewshot:
  - 0
  batch_size: 16
  icl_task_type: language_modeling
  metric_names:
  - InContextLearningLMAccuracy
  prompt_string: '' # this goes at the beginning of each input
  example_delimiter: '\n' # this goes between fewshot examples
  continuation_delimiter: ' ' # this separates contexts from continuations
