integrations:
- integration_type: git_repo
  git_repo: mosaicml/llm-foundry
  git_branch: icl_eval_categories # use your branch
  # git_commit: # OR use your commit hash
  pip_install: -e ".[gpu]"
  ssh_clone: false # Should be true if using a private repo

command: |
  cd llm-foundry
  composer llmfoundry/icl_eval/evaluate_model.py /mnt/config/parameters.yaml

image: mosaicml/pytorch:1.13.1_cu117-python3.10-ubuntu20.04

# Mosaic Cloud will use run_name (with a unique suffix) to populate the env var $COMPOSER_RUN_NAME
# run_name: mpt-7b-eval
run_name: llama-eval
gpu_num: 32
gpu_type: a100_40gb
cluster: r7z2 # replace with your cluster here!

# The below is injected as a YAML file: /mnt/config/parameters.yaml
parameters: 
    # Tokenizer
  tokenizer:
      # name: EleutherAI/gpt-j-6b
      # name: EleutherAI/pythia-6.9b
      # name: facebook/opt-6.7b
      # name: cerebras/Cerebras-GPT-6.7B
      # name: StabilityAI/stablelm-base-alpha-7b
      name: huggyllama/llama-7b
      # name: EleutherAI/gpt-neox-20b
      # name: EleutherAI/pythia-12b
      # name: facebook/opt-13b
      # name: cerebras/Cerebras-GPT-13B
      kwargs:
        model_max_length: 1024

  model:
    name: hf_causal_lm
    # pretrained_model_name_or_path: EleutherAI/gpt-j-6b
    # pretrained_model_name_or_path: EleutherAI/pythia-6.9b
    # pretrained_model_name_or_path: facebook/opt-6.7b
    # pretrained_model_name_or_path: cerebras/Cerebras-GPT-6.7B
    # pretrained_model_name_or_path: StabilityAI/stablelm-base-alpha-7b
    pretrained_model_name_or_path: huggyllama/llama-7b
    # pretrained_model_name_or_path: EleutherAI/gpt-neox-20b
    # pretrained_model_name_or_path: EleutherAI/pythia-12b
    # pretrained_model_name_or_path: facebook/opt-13b
    # pretrained_model_name_or_path: cerebras/Cerebras-GPT-13B
    device: cpu
    pretrained: true

  # FSDP config for model sharding
  fsdp_config:
    sharding_strategy: FULL_SHARD
    mixed_precision: PURE

  icl_tasks:
    -
      label: jeopardy
      dataset_uri: llmfoundry/icl_eval/local_data/jeopardy_all.jsonl # ADD YOUR OWN DATASET URI
      num_fewshot:
      - 0
      - 1
      - 5
      - 10
      batch_size: 8
      icl_task_type: language_modeling
      metric_names:
      - InContextLearningLMAccuracy
      prompt_string: "" # this goes at the beginning of each input
      example_delimiter: "\n" # this goes between fewshot examples
      continuation_delimiter: "\nAnswer: " # this separates questions from answers
      has_categories: true
    -
      label: lambada_openai
      dataset_uri: llmfoundry/icl_eval/local_data/lambada_openai.jsonl 
      num_fewshot:
      - 0
      batch_size: 8
      icl_task_type: language_modeling
      metric_names:
      - InContextLearningLMAccuracy
      prompt_string: "" # this goes at the beginning of each input
      example_delimiter: "\n" # this goes between fewshot examples
      continuation_delimiter: " " # this separates contexts from continuations
    -
      label: piqa
      dataset_uri:  llmfoundry/icl_eval/local_data/piqa.jsonl  # ADD YOUR OWN DATASET URI
      num_fewshot:
      - 0
      - 1
      - 5
      - 10
      batch_size: 8
      icl_task_type: multiple_choice
      metric_names:
      - InContextLearningMultipleChoiceAccuracy
      prompt_string: "" # this goes at the beginning of each input
      example_delimiter: "\n" # this goes between fewshot examples
      continuation_delimiter: "Answer: " # this separates questions from answers
    -
      label: hellaswag
      dataset_uri: llmfoundry/icl_eval/local_data/hellaswag.jsonl # ADD YOUR OWN DATASET URI
      num_fewshot:
      - 0
      - 1
      - 5
      - 10
      batch_size: 8
      icl_task_type: multiple_choice
      metric_names:
      - InContextLearningMultipleChoiceAccuracy
      prompt_string: "" # this goes at the beginning of each input
      example_delimiter: "\n" # this goes between fewshot examples
      continuation_delimiter: " " # this separates questions from answers
    -
      label: arc_easy
      dataset_uri: llmfoundry/icl_eval/local_data/arc_easy.jsonl # ADD YOUR OWN DATASET URI
      num_fewshot:
      - 0
      - 1
      - 5
      - 10
      batch_size: 8
      icl_task_type: multiple_choice
      metric_names:
      - InContextLearningMultipleChoiceAccuracy
      prompt_string: "" # this goes at the beginning of each input
      example_delimiter: "\n" # this goes between fewshot examples
      continuation_delimiter: "Answer: " # this separates questions from answers
    -
      label: arc_challenge
      dataset_uri: llmfoundry/icl_eval/local_data/arc_challenge.jsonl # ADD YOUR OWN DATASET URI
      num_fewshot:
      - 0
      - 1
      - 5
      - 10
      batch_size: 8
      icl_task_type: multiple_choice
      metric_names:
      - InContextLearningMultipleChoiceAccuracy
      prompt_string: "" # this goes at the beginning of each input
      example_delimiter: "\n" # this goes between fewshot examples
      continuation_delimiter: "Answer: " # this separates questions from answers
    -
      label: copa
      dataset_uri: llmfoundry/icl_eval/local_data/copa.jsonl # ADD YOUR OWN DATASET URI
      num_fewshot:
      - 0
      - 1
      - 5
      - 10
      batch_size: 8
      icl_task_type: multiple_choice
      metric_names:
      - InContextLearningMultipleChoiceAccuracy
      prompt_string: "" # this goes at the beginning of each input
      example_delimiter: "\n" # this goes between fewshot examples
      continuation_delimiter: " " # this separates questions from answers
    -
      label: boolq
      dataset_uri: llmfoundry/icl_eval/local_data/boolq.jsonl # ADD YOUR OWN DATASET URI
      num_fewshot:
      - 0
      - 1
      - 5
      - 10
      batch_size: 8
      icl_task_type: multiple_choice
      metric_names:
      - InContextLearningMultipleChoiceAccuracy
      prompt_string: "" # this goes at the beginning of each input
      example_delimiter: "\n" # this goes between fewshot examples
      continuation_delimiter: "Answer: " # this separates questions from answers
    -
      label: mmlu
      dataset_uri: llmfoundry/icl_eval/local_data/mmlu.jsonl # ADD YOUR OWN DATASET URI
      num_fewshot:
      - 0
      - 1
      - 5
      - 10
      batch_size: 8
      icl_task_type: multiple_choice
      metric_names:
      - InContextLearningMultipleChoiceAccuracy
      prompt_string: "" # this goes at the beginning of each input
      example_delimiter: "\n" # this goes between fewshot examples
      continuation_delimiter: "Answer: " # this separates questions from answers
      has_categories: true
    -
      label: winograd
      dataset_uri: llmfoundry/icl_eval/local_data/winograd_wsc.jsonl # ADD YOUR OWN DATASET URI
      num_fewshot:
      - 0
      - 1
      - 5
      - 10
      batch_size: 8
      icl_task_type: schema
      metric_names:
      - InContextLearningMultipleChoiceAccuracy
      prompt_string: "" # this goes at the beginning of each input
      example_delimiter: "\n" # this goes between fewshot examples
      continuation_delimiter: " " # this separates questions from answers
    -
      label: winogrande
      dataset_uri: llmfoundry/icl_eval/local_data/winogrande.jsonl # ADD YOUR OWN DATASET URI
      num_fewshot:
      - 0
      - 1
      - 5
      - 10
      batch_size: 8
      icl_task_type: schema
      metric_names:
      - InContextLearningMultipleChoiceAccuracy
      prompt_string: "" # this goes at the beginning of each input
      example_delimiter: "\n" # this goes between fewshot examples
      continuation_delimiter: " " # this separates questions from answers
    -
      label: triviaqa
      dataset_uri: llmfoundry/icl_eval/local_data/triviaqa.jsonl # ADD YOUR OWN DATASET URI
      num_fewshot:
      - 0
      - 1
      - 5
      - 10
      batch_size: 8
      icl_task_type: question_answering
      metric_names:
      - InContextLearningQAAccuracy
      prompt_string: "" # this goes at the beginning of each input
      example_delimiter: "\n" # this goes between fewshot examples
      continuation_delimiter: " " # this separates questions from answers
