#!/bin/bash
#PBS -l select=1:ngpus=8
#PBS -l walltime=96:00:00
#PBS -N llmfoundry_nsa_profile
#PBS -o out_nsa.txt
#PBS -j oe
#PBS -q ic102
#PBS -P 71001002

# Exit on any error
set -e

# Deactivate any existing env and activate LLM Foundry virtual env
deactivate || true
cd llm-foundry/
source .venv/bin/activate 
cd scripts

# Logging

export NSYS_NVTX_PROFILER_REGISTER_ONLY=0 
echo "done here" >> out_nsa.txt 

# NCCL safety exports
export NCCL_ASYNC_ERROR_HANDLING=1  
export TORCH_NCCL_BLOCKING_WAIT_TIMEOUT_MS=900000 

# Run with NVIDIA Nsight Systems profiler
composer train/train.py \
  train/yamls/pretrain/mpt-350m-nsa.yaml \
  variables.data_local=/home/users/nus/e1113744/scratch/c4_long_seq \
  train_loader.dataset.split=train \
  eval_loader.dataset.split=val \
  max_duration=800ba \
  eval_interval=0 \
  save_folder=mpt-350m-nsa >> out_nsa.txt

