name: Docker build
on:
  push:
    branches:
    - main
  workflow_dispatch: {}
jobs:
  docker-build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'mosaicml'
    strategy:
      fail-fast: false
      matrix:
        example:
        - llm
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Calculate Docker Image Variables
      run: |
        set -euxo pipefail

        ###################
        # Calculate the tag
        ###################
        GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        echo "IMAGE_TAG=${GIT_SHA}" >> ${GITHUB_ENV}

    - name: Build and Push the Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        tags: >-
          mosaicml/examples:${{ matrix.example }}-latest,
          mosaicml/examples:${{ matrix.example }}-${{ env.IMAGE_TAG }}
        push: ${{ contains(github.ref, 'refs/heads/main') }}
        cache-from: type=registry,ref=mosaicml/examples:${{ matrix.example }}-buildcache
        cache-to: type=registry,ref=mosaicml/examples:${{ matrix.example }}-buildcache,mode=max
        build-args: EXAMPLE=${{ matrix.example }}
