name: Test

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*
  workflow_dispatch: {}
defaults:
  run:
    working-directory: .
jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    name: ${{ matrix.name }}
    container: mosaicml/pytorch:1.13.1_cpu-python3.10-ubuntu20.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        set -ex
        export PATH=/composer-python:$PATH
        python -m pip install --upgrade 'pip<23' wheel
    - name: Test
      run: |
        export PATH=/composer-python:$PATH
        bash scripts/test.sh
